# Generated by Django 3.1.2 on 2021-01-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20201203_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlike',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='learn.lesson', verbose_name='lesson'),
        ),
    ]
