# Generated by Django 3.1.2 on 2021-03-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20210126_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], default='A', max_length=2, verbose_name='group'),
        ),
    ]
