# Generated by Django 3.1.2 on 2021-01-08 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_habit_is_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='habit', to='habit.goal', verbose_name='goal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 8)),
        ),
    ]
