# Generated by Django 3.1.2 on 2021-01-09 14:33

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_auto_20210108_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateField(blank=True, default=now().date().today()),
        ),
    ]
