# Generated by Django 3.1.2 on 2021-01-25 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_auto_20210109_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 25)),
        ),
    ]
