# Generated by Django 3.1.2 on 2021-02-22 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_auto_20210126_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 22)),
        ),
    ]
