# Generated by Django 3.1.2 on 2021-03-01 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_auto_20210222_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 1)),
        ),
    ]
